#!/usr/bin/env python3
"""
Tests for the delete guards (AUDIT F-03) and the isolation config invariant.

Run from the repository root:

    python3 tests/test_safety_guards.py

Three destructive operations in this package take their target from an
operator-supplied argument, and two of them run as root during installation:

  * realism/build_profile.py --out ...   replaces a directory
  * dashboard/bundle.py     --out ...    replaces a directory
  * deploy/uninstall.sh     --remove     deletes the state directory

The failure this suite exists to prevent is `--out /opt/cowrie` (the state
directory, i.e. the recordings) where the operator meant `build/profile`. The
guard's rule is that a recursive delete must be shown to be this package's own
output, and "not shown" means refuse -- so the tests below are mostly negative:
they assert that plausible-but-wrong paths are refused, with the data intact.

The last class checks the invariant the audit asked for by name:
`forward_redirect` and `forward_tunnel` must be false, because everything the
isolation story claims about port forwarding depends on those two values and
nothing read them.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
for sub in ("shared", "dashboard"):
    p = str(ROOT / sub)
    if p not in sys.path:
        sys.path.insert(0, p)
sys.path.insert(0, str(ROOT / "tests" / "lib"))

from config_check import isolation_config_problems  # noqa: E402
from safe_paths import (DEFAULT_STATE_DIR, MARKER_BUNDLE, MARKER_PROFILE,  # noqa: E402
                        UnsafePathError, guard_delete_target, looks_like_state_dir,
                        write_marker)

GUARDS_SH = ROOT / "deploy" / "lib" / "guards.sh"
UNINSTALL_SH = ROOT / "deploy" / "uninstall.sh"
VERSIONS_ENV = ROOT / "deploy" / "versions.env"
VENV_PYTHON = ROOT / ".venv" / "bin" / "python"


def run_guard(path: str, force: str = "0") -> subprocess.CompletedProcess:
    """Call the shell guard the way uninstall.sh does."""
    script = (f'source "{GUARDS_SH}"\n'
              f'guard_delete_target_state_dir "$1" "$2"\n')
    return subprocess.run(["bash", "-c", script, "guard", path, force],
                          capture_output=True, text=True, timeout=30)


class GuardTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="guard-test-"))
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)

    def make_dir(self, *parts: str) -> Path:
        path = self.tmp.joinpath(*parts)
        path.mkdir(parents=True, exist_ok=True)
        return path


# ----------------------------------------------------------------------
# The Python guard
# ----------------------------------------------------------------------

class TestPythonGuard(GuardTestCase):
    def test_system_directories_are_refused_even_with_force(self) -> None:
        for bad in ("/", "/etc", "/usr", "/var", "/opt", "/home", "/tmp"):
            with self.subTest(path=bad):
                with self.assertRaises(UnsafePathError):
                    guard_delete_target(Path(bad), kind="profile-output", allow_force=True)

    def test_the_working_directory_and_its_ancestors_are_refused(self) -> None:
        with self.assertRaises(UnsafePathError):
            guard_delete_target(Path.cwd(), kind="bundle-output", allow_force=True)
        with self.assertRaises(UnsafePathError):
            guard_delete_target(Path.cwd().parent, kind="bundle-output", allow_force=True)

    def test_an_unrelated_directory_is_refused_and_survives(self) -> None:
        target = self.make_dir("not-ours")
        (target / "important.txt").write_text("keep me")
        with self.assertRaises(UnsafePathError) as ctx:
            guard_delete_target(target, kind="profile-output")
        self.assertIn("does not look like", str(ctx.exception))
        self.assertTrue((target / "important.txt").is_file())

    def test_force_allows_an_unmarked_directory(self) -> None:
        target = self.make_dir("not-ours")
        self.assertEqual(
            guard_delete_target(target, kind="profile-output", allow_force=True), target)

    def test_a_directory_under_build_is_recognised(self) -> None:
        target = self.make_dir("build", "profile")
        self.assertEqual(guard_delete_target(target, kind="profile-output"), target)

    def test_a_marker_from_a_previous_run_is_recognised(self) -> None:
        target = self.make_dir("somewhere", "out")
        write_marker(target, MARKER_PROFILE, "generated by a test")
        self.assertEqual(guard_delete_target(target, kind="profile-output"), target)

    def test_a_missing_path_is_not_an_error(self) -> None:
        target = self.tmp / "does-not-exist"
        self.assertEqual(guard_delete_target(target, kind="profile-output"), target)

    def test_an_empty_path_is_refused(self) -> None:
        with self.assertRaises(UnsafePathError):
            guard_delete_target(Path(""), kind="profile-output", allow_force=True)

    def test_a_symlink_is_refused(self) -> None:
        real = self.make_dir("build", "real")
        link = self.tmp / "link"
        link.symlink_to(real)
        with self.assertRaises(UnsafePathError):
            guard_delete_target(link, kind="profile-output", allow_force=True)
        self.assertTrue(real.is_dir(), "the symlink target was deleted")

    def test_a_mount_point_is_refused(self) -> None:
        with self.assertRaises(UnsafePathError) as ctx:
            guard_delete_target(Path("/proc"), kind="state-dir", allow_force=True)
        self.assertIn("mount point", str(ctx.exception))

    def test_bundle_output_rules(self) -> None:
        empty = self.make_dir("empty-bundle")
        self.assertEqual(guard_delete_target(empty, kind="bundle-output"), empty)
        full = self.make_dir("full-bundle")
        (full / "something.txt").write_text("data")
        with self.assertRaises(UnsafePathError):
            guard_delete_target(full, kind="bundle-output")
        write_marker(full, MARKER_BUNDLE, "written by a test")
        self.assertEqual(guard_delete_target(full, kind="bundle-output"), full)

    def test_state_dir_rules(self) -> None:
        state = self.make_dir("cowrie")
        (state / "var" / "lib" / "cowrie" / "tty").mkdir(parents=True)
        self.assertTrue(looks_like_state_dir(state))
        self.assertEqual(guard_delete_target(state, kind="state-dir"), state)

        unrelated = self.make_dir("home")
        (unrelated / "notes.txt").write_text("not a honeypot")
        with self.assertRaises(UnsafePathError):
            guard_delete_target(unrelated, kind="state-dir")
        self.assertEqual(guard_delete_target(unrelated, kind="state-dir", allow_force=True),
                         unrelated)


# ----------------------------------------------------------------------
# The shell guard
# ----------------------------------------------------------------------

class TestShellGuard(GuardTestCase):
    """The same rules, because uninstall.sh cannot import a Python module."""

    def test_repository_layout_is_as_expected(self) -> None:
        self.assertTrue(GUARDS_SH.is_file(), f"{GUARDS_SH} is missing")

    def test_system_and_shared_directories_are_refused(self) -> None:
        for bad in ("/", "/etc", "/opt", "/var", "/home", "/usr"):
            with self.subTest(path=bad):
                proc = run_guard(bad)
                self.assertNotEqual(proc.returncode, 0)
                self.assertIn("refusing", proc.stderr)

    def test_an_unmarked_directory_is_refused_unless_forced(self) -> None:
        target = self.make_dir("unrelated")
        proc = run_guard(str(target))
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("does not look like", proc.stderr)

        forced = run_guard(str(target), force="1")
        self.assertEqual(forced.returncode, 0)
        self.assertEqual(forced.stdout.strip(), str(target))

    def test_a_state_directory_layout_is_accepted(self) -> None:
        state = self.make_dir("state")
        (state / "var" / "lib" / "cowrie" / "tty").mkdir(parents=True)
        proc = run_guard(str(state))
        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout.strip(), str(state))

    def test_the_script_cannot_delete_a_path_it_did_not_check(self) -> None:
        """
        The delete must act on the guard's RESOLVED path.

        Before the fix the last line was `rm -rf "$STATE_DIR"`, so the checked
        value and the deleted value could differ (STATE_DIR is overridable in
        /etc/cowrie-logship.env). Asserting on the source is crude, but the
        alternative is running a destructive script as root in a test.
        """
        text = UNINSTALL_SH.read_text(encoding="utf-8")
        self.assertIn("guard_delete_target_state_dir", text)
        self.assertIn('rm -rf "$RESOLVED_STATE_DIR"', text)
        self.assertNotIn('rm -rf "$STATE_DIR"', text)
        self.assertIn("deploy/lib/guards.sh", text)
        # The guard must be sourced, not merely mentioned in a comment.
        self.assertRegex(text, "(?m)^source .*deploy/lib/guards[.]sh")

    def test_every_rm_rf_in_the_scripts_targets_a_checked_or_literal_path(self) -> None:
        findings: list[str] = []
        for script in sorted((ROOT / "deploy").rglob("*.sh")) + sorted((ROOT / "ops").rglob("*.sh")):
            for line in script.read_text(encoding="utf-8").splitlines():
                stripped = line.strip()
                if "rm -rf" not in stripped or stripped.startswith("#"):
                    continue
                findings.append(f"{script.relative_to(ROOT)}: {stripped}")
        self.assertEqual(
            findings, ["deploy/uninstall.sh: rm -rf \"$RESOLVED_STATE_DIR\""],
            "a new recursive delete appeared; give it a guard or explain it here")


class TestGuardConsistency(unittest.TestCase):
    def test_default_state_dir_agrees_across_three_files(self) -> None:
        versions = subprocess.run(
            ["bash", "-c", f'source "{VERSIONS_ENV}"; printf "%s" "$STATE_DIR"'],
            capture_output=True, text=True, timeout=30)
        self.assertEqual(versions.returncode, 0, versions.stderr)
        self.assertEqual(versions.stdout, DEFAULT_STATE_DIR,
                         "shared/safe_paths.py and deploy/versions.env disagree")

        shell = subprocess.run(
            ["bash", "-c", f'source "{GUARDS_SH}"; printf "%s" "$DEFAULT_STATE_DIR"'],
            capture_output=True, text=True, timeout=30)
        self.assertEqual(shell.stdout, DEFAULT_STATE_DIR,
                         "deploy/lib/guards.sh and shared/safe_paths.py disagree")


# ----------------------------------------------------------------------
# The callers
# ----------------------------------------------------------------------

class TestProfileBuilderRefusesUnsafeOutput(GuardTestCase):
    """
    End to end through the real CLI: the refusal must happen before the
    delete, and the data must still be there afterwards.
    """

    def setUp(self) -> None:
        super().setUp()
        if not VENV_PYTHON.exists():
            self.skipTest("no .venv; run the local validation setup in the README")
        probe = subprocess.run([str(VENV_PYTHON), "-c", "import yaml, cowrie"],
                               capture_output=True, text=True)
        if probe.returncode != 0:
            self.skipTest(f"the venv lacks PyYAML/Cowrie: {probe.stderr.strip()[:120]}")

    def build(self, out: str, *extra: str, cwd: Path | None = None):
        return subprocess.run(
            [str(VENV_PYTHON), str(ROOT / "realism" / "build_profile.py"),
             "--identity", str(ROOT / "realism" / "identity.yaml"),
             "--now", "2026-10-04T00:00:00Z", "--out", out, *extra],
            capture_output=True, text=True, cwd=str(cwd or self.tmp), timeout=600)

    def test_a_directory_that_is_not_ours_is_refused_and_survives(self) -> None:
        victim = self.make_dir("opt", "cowrie", "var", "lib", "cowrie", "tty")
        (victim / "recording").write_bytes(b"session recording evidence")
        proc = self.build(str(self.tmp / "opt" / "cowrie"))
        self.assertEqual(proc.returncode, 2, proc.stdout + proc.stderr)
        self.assertIn("refusing to delete", proc.stderr)
        self.assertTrue((victim / "recording").is_file(), "evidence was deleted anyway")

    def test_the_documented_invocation_works_and_leaves_a_marker(self) -> None:
        proc = self.build("build/profile")
        self.assertEqual(proc.returncode, 0, proc.stderr[-2000:])
        profile = self.tmp / "build" / "profile"
        self.assertTrue((profile / "fs.pickle").is_file())
        self.assertTrue((profile / MARKER_PROFILE).is_file(),
                        "a successful build did not mark its output, so the next "
                        "build will refuse to refresh it")
        # Second run: recognised by the marker, no force needed.
        again = self.build("build/profile")
        self.assertEqual(again.returncode, 0, again.stderr[-2000:])

    def test_force_overrides_only_the_ownership_check(self) -> None:
        target = self.make_dir("scratch")
        (target / "old").write_text("stale")
        proc = self.build(str(target))
        self.assertEqual(proc.returncode, 2)
        proc = self.build(str(target), "--force-recursive-delete")
        self.assertEqual(proc.returncode, 0, proc.stderr[-2000:])
        self.assertFalse((target / "old").exists(), "the directory was not replaced")


class TestBundleBuilderGuard(GuardTestCase):
    def test_refuses_a_non_bundle_directory(self) -> None:
        import bundle
        state = self.make_dir("state")
        target = self.make_dir("not-a-bundle")
        (target / "keep.txt").write_text("data")
        with self.assertRaises(SystemExit) as ctx:
            bundle.build_bundle(state, target)
        self.assertEqual(ctx.exception.code, 2)
        self.assertTrue((target / "keep.txt").is_file())


# ----------------------------------------------------------------------
# The isolation invariant (the audit's closing recommendation)
# ----------------------------------------------------------------------

class TestIsolationConfig(unittest.TestCase):
    def test_the_shipped_config_is_safe(self) -> None:
        problems = isolation_config_problems(ROOT / "config" / "cowrie.cfg")
        self.assertEqual(problems, [], "\n".join(problems))

    def test_the_check_catches_a_reopened_forward(self) -> None:
        """Negative control: a guard that cannot fail is not a guard."""
        tmp = Path(tempfile.mkdtemp(prefix="cfg-test-"))
        self.addCleanup(shutil.rmtree, tmp, ignore_errors=True)
        cfg = tmp / "cowrie.cfg"
        cfg.write_text("[ssh]\nforwarding = true\nforward_redirect = true\n"
                       "forward_tunnel = false\n", encoding="utf-8")
        problems = isolation_config_problems(cfg)
        self.assertTrue(problems)
        self.assertIn("forward_redirect", problems[0])

    def test_missing_section_is_reported(self) -> None:
        tmp = Path(tempfile.mkdtemp(prefix="cfg-test-"))
        self.addCleanup(shutil.rmtree, tmp, ignore_errors=True)
        cfg = tmp / "cowrie.cfg"
        cfg.write_text("[shell]\nfoo = bar\n", encoding="utf-8")
        self.assertTrue(isolation_config_problems(cfg))


class TestSharedLibraryResolution(unittest.TestCase):
    """
    Every module that needs shared/ must be able to find it in both places it
    exists: beside the package (a checkout, and the installed copy -- both have
    shared/ one level up from dashboard/) and under the state directory that
    deploy/install.sh populates.

    The second fallback used to read /opt/honeypot-monitor/share, which no
    installer or document in this repository has ever created, so it had never
    resolved. These tests keep a real path there and keep the phantom out.
    """

    REPO = Path(__file__).resolve().parent.parent

    def test_no_module_references_a_path_the_installer_never_creates(self) -> None:
        offenders = []
        for path in sorted(self.REPO.rglob("*")):
            rel = path.relative_to(self.REPO)
            if path.suffix not in (".py", ".sh") or path.is_dir():
                continue
            if rel.parts[0] in (".git", "lab", "build", "tests"):
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if "/opt/honeypot-monitor" in text:
                offenders.append(str(rel))
        self.assertEqual(offenders, [],
                         "these ship a shared/ fallback path that nothing creates: "
                         + ", ".join(offenders))

    def test_the_state_directory_fallback_resolves_shared(self) -> None:
        """
        Run the dashboard modules from a copy that has no sibling shared/, with
        HONEYPOT_STATE_DIR pointing at a host layout that does. If the fallback
        is real, they import; if it is a phantom, they die with an ImportError.
        """
        tmp = Path(tempfile.mkdtemp(prefix="shared-resolution-"))
        self.addCleanup(shutil.rmtree, tmp, ignore_errors=True)

        partial = tmp / "partial"
        (partial / "dashboard").parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(self.REPO / "dashboard", partial / "dashboard",
                        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))

        host = tmp / "host"
        shared_dst = host / "share" / "pkg" / "shared"
        shared_dst.mkdir(parents=True)
        for src in sorted((self.REPO / "shared").glob("*.py")):
            shutil.copy2(src, shared_dst / src.name)

        env = dict(os.environ, HONEYPOT_STATE_DIR=str(host), PYTHONDONTWRITEBYTECODE="1")
        proc = subprocess.run(
            [sys.executable, "-c",
             "import sys; sys.path.insert(0, %r)\n"
             "import store, auth, render, bundle\n"
             "import safe_paths, terminal_safety\n"
             "print(safe_paths.__file__); print(terminal_safety.__file__)\n"
             % str(partial / "dashboard")],
            capture_output=True, text=True, env=env, timeout=120,
            cwd=str(tmp))
        self.assertEqual(proc.returncode, 0,
                         "the modules could not find shared/ via "
                         "HONEYPOT_STATE_DIR:\n" + proc.stderr[-2000:])
        self.assertIn(str(shared_dst), proc.stdout,
                      "shared/ was not loaded from the state directory")

    def test_a_checkout_without_shared_fails_loudly(self) -> None:
        """Negative control: with neither candidate present, the failure is
        explicit rather than a silent fallback to stale code."""
        tmp = Path(tempfile.mkdtemp(prefix="no-shared-"))
        self.addCleanup(shutil.rmtree, tmp, ignore_errors=True)
        (tmp / "dashboard").parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(self.REPO / "dashboard", tmp / "dashboard",
                        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        env = dict(os.environ, HONEYPOT_STATE_DIR=str(tmp / "empty"),
                   PYTHONDONTWRITEBYTECODE="1")
        proc = subprocess.run(
            [sys.executable, "-c",
             "import sys; sys.path.insert(0, %r)\nimport store\n"
             % str(tmp / "dashboard")],
            capture_output=True, text=True, env=env, timeout=120, cwd=str(tmp))
        self.assertNotEqual(proc.returncode, 0)
        self.assertIn("No module named", proc.stderr)


class TestShippedScriptModes(unittest.TestCase):
    """
    A script the documentation tells a user to run must be runnable.

    docs/03-install-ubuntu-ec2.md says `sudo ./deploy/install.sh --apply`.
    install.sh was committed 0644 while every other shipped script was 0755, so
    that exact command failed with "permission denied" on a fresh clone. The
    shell scripts under a lib/ directory are sourced, not executed, and are
    allowed to be non-executable.
    """

    REPO = Path(__file__).resolve().parent.parent

    def test_executable_scripts_have_the_executable_bit(self) -> None:
        offenders = []
        for path in sorted(self.REPO.rglob("*.sh")):
            rel = path.relative_to(self.REPO)
            if rel.parts[0] in (".git", ".venv", "build", "lab"):
                continue
            if "lib" in rel.parts[:-1]:
                continue  # sourced, never executed
            try:
                first = path.open("r", encoding="utf-8", errors="replace").readline()
            except OSError:
                continue
            if not first.startswith("#!"):
                continue  # not a directly runnable script
            if not os.access(path, os.X_OK):
                offenders.append(str(rel))
        self.assertEqual(offenders, [],
                         "these are executed directly but are not executable: "
                         + ", ".join(offenders))

    def test_the_documented_install_command_is_runnable(self) -> None:
        """Negative control tied to the exact invocation in the docs."""
        install = self.REPO / "deploy" / "install.sh"
        self.assertTrue(os.access(install, os.X_OK),
                        "docs/03 tells the reader to run `sudo ./deploy/install.sh`")


if __name__ == "__main__":
    unittest.main(verbosity=2)
